version: '3.8'

services:
  django:
    build: .
    # command: python3 manage.py runserver 127.0.0.1:8000 #gunicorn project.wsgi 127.0.0.1:8000
    # volumes:
    #   - ./app/:/usr/src/app/
    # ports:
    #   - 8000:8000
    # environment:
    #   TZ: Europe/Amsterdam
    # env_file:
    #   - ./.env.dev
    # entrypoint: entrypoint.sh
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: booksuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: booksdatabase

  nginx:
    image: nginx:1.19.0-alpine
    ports:
      - "80:80"
    volumes:
      - nginx_conf:/etc/nginx/conf.d/
    depends_on:
      - django
    restart: always

volumes:
  postgres_data:
  nginx_conf: