# Generated by Django 4.0 on 2023-11-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
