# Generated by Django 4.0 on 2023-11-05 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='favorite',
        ),
    ]
